const nodeDesc = [
    "nodeIndex",
    "status";
    "familyName",
    "firstName",
    "birthDate",
    "birthCity",
    "birthCountry",
    "birthContinent",
    "profileImage",
    "freeText",
    "dadIndex",
    "momIndex"
];

let familyTree_TESTDATA = [{
        "nodeIndex": 1,
        "status": "active",
        "familyName": "Dupond",
        "firstName": "Jean",
        "gender": "M",
        "birthDate": "19950423",
        "birthDate_heb": "24Nisan5755",
        "birthCity": "",
        "birthCountry": "",
        "birthContinent": "Europe",
        "profileImage": "TESTDATA1.png",
        "freeText": "This is a sample text",
        "dadIndex": 3,
        "momIndex": 2,
    },
    {
        "nodeIndex": 2,
        "status": "active",
        "familyName": "Martin",
        "firstName": "Amélie",
        "gender": "F",
        "birthDate": "19700813",
        "birthDate_heb": "",
        "birthCity": "",
        "birthCountry": "",
        "birthContinent": "Europe",
        "profileImage": "TESTDATA2.png",
        "freeText": "This is a sample text",
        "dadIndex": 0,
        "momIndex": 0,
    },
    {
        "nodeIndex": 3,
        "status": "active",
        "familyName": "Dupond",
        "firstName": "Andrei",
        "gender": "F",
        "birthDate": "19690903",
        "birthDate_heb": "",
        "birthCity": "",
        "birthCountry": "",
        "birthContinent": "America",
        "profileImage": "TESTDATA2.png",
        "freeText": "This is a sample text",
        "dadIndex": 0,
        "momIndex": 0,
    }
];